-- Body Rebuild Restart Assessment — authoritative submission store.
-- Handoff §13.1 / §13.2.
--
-- This table, not GoHighLevel, is the system of record. It exists so that a CRM
-- outage cannot lose a lead, a double-click cannot create two contacts, and a
-- scoring change years from now can still be traced back to what a given
-- visitor was actually told (§24.3).
--
-- Target: any PostgreSQL 13+ (Neon, Supabase, Vercel Postgres).
-- Apply with: psql "$DATABASE_URL" -f migrations/001_assessment_submissions.sql

-- No CREATE EXTENSION here on purpose: gen_random_uuid() is built into
-- PostgreSQL 13+, and CREATE EXTENSION needs privileges some managed hosts
-- (and some read-only migration roles) do not grant.

create table if not exists assessment_submissions (
  id                     uuid primary key default gen_random_uuid(),

  -- Idempotency key generated by the browser before the first attempt (§9.1).
  -- The unique constraint is what makes double-clicks and network retries safe.
  client_submission_id   uuid        not null unique,

  first_name             text        not null,
  normalized_email       text        not null,
  normalized_phone       text        not null,

  age_range              text        not null,
  training_environment   text        not null,
  main_goal              text        not null,
  biggest_obstacle       text        not null,

  -- Consent is evidence, not a preference: store what was agreed and when.
  email_consent          boolean     not null,
  sms_consent            boolean     not null default false,
  consent_timestamp      timestamptz not null,

  answers_json           jsonb       not null,
  scores_json            jsonb       not null,
  results_json           jsonb       not null,
  attribution_json       jsonb       not null default '{}'::jsonb,

  -- Stamped on every row so a future scoring change is auditable (§24.3).
  assessment_version     text        not null,
  scoring_version        text        not null,
  result_content_version text        not null,
  result_token_version   text        not null default 'v1',

  -- GoHighLevel synchronization state (§13.4). Deliberately separate from the
  -- submission itself: the lead is saved and the visitor sees their result
  -- whether or not the CRM was reachable.
  ghl_contact_id         text,
  ghl_sync_status        text        not null default 'pending',
  ghl_sync_attempts      integer     not null default 0,
  ghl_last_attempt_at    timestamptz,
  ghl_last_error_code    text,
  workflow_enrolled_at   timestamptz,

  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),

  constraint assessment_submissions_ghl_sync_status_check
    check (ghl_sync_status in ('pending', 'synced', 'retry_required', 'permanent_failure')),

  -- §11.2: email consent must be true for a submission to exist at all.
  constraint assessment_submissions_email_consent_check
    check (email_consent = true)
);

-- Looking up a person's history by email (support requests, re-submissions).
create index if not exists assessment_submissions_email_idx
  on assessment_submissions (normalized_email);

-- Drives the retry worker (§20.4): find the oldest rows still awaiting sync.
create index if not exists assessment_submissions_retry_idx
  on assessment_submissions (ghl_sync_status, ghl_last_attempt_at)
  where ghl_sync_status in ('pending', 'retry_required');

-- Contacts that reached GoHighLevel but never got enrolled in the Day 0
-- workflow. Tracked separately from ghl_sync_status because the upsert
-- succeeding and the enrollment succeeding are independent outcomes — these
-- are the people who would silently never receive their result email.
create index if not exists assessment_submissions_enroll_retry_idx
  on assessment_submissions (ghl_last_attempt_at)
  where ghl_contact_id is not null and workflow_enrolled_at is null;

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists assessment_submissions_set_updated_at on assessment_submissions;
create trigger assessment_submissions_set_updated_at
  before update on assessment_submissions
  for each row execute function set_updated_at();
